// <auto-generated />
namespace ApplicationFile.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class catagoryModelChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(catagoryModelChange));
        
        string IMigrationMetadata.Id
        {
            get { return "201807240524276_catagoryModelChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
