// <auto-generated />
namespace ApplicationFile.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CatagoryAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CatagoryAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201807151911501_CatagoryAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
